"""Sparse LLM judge core: backends, the Judge facade, and prompt handling.

The judge is used ONLY where programmatic grading is impossible (open-ended
synthesis quality, free-text rationale checks) and ONLY at episode boundaries —
never per step and never inside the agent loop.  Its tokens are an auditing cost
and are EXCLUDED from the system ``CostVector`` (see :class:`JudgeUsage`).

The real model is config-pinned (id + revision come from :class:`JudgeConfig`,
never hard-coded here) and loaded only behind the ``LHMSB_LIVE_JUDGE=1`` env gate.
A deterministic :class:`StubJudge` backend is provided for unit tests.
"""

from __future__ import annotations

import importlib
import json
import os
import re
from collections.abc import Callable
from dataclasses import dataclass
from typing import Protocol

from lhmsb.judge.config import JudgeConfig
from lhmsb.judge.rubric import Rubric
from lhmsb.judge.trace import JudgeTraceLog, JudgeTraceRecord
from lhmsb.types import Probe

LIVE_JUDGE_ENV_FLAG = "LHMSB_LIVE_JUDGE"


# --------------------------------------------------------------------------- #
# Errors
# --------------------------------------------------------------------------- #
class JudgeError(Exception):
    """Base class for judge errors."""


class JudgeUsageError(JudgeError):
    """Raised when the judge is used outside its sparse, boundary-only contract."""


class JudgeUnavailableError(JudgeError):
    """Raised when the live judge model cannot be loaded (e.g. env flag unset)."""


# --------------------------------------------------------------------------- #
# Value types
# --------------------------------------------------------------------------- #
@dataclass(frozen=True)
class JudgeScore:
    """A structured judge verdict.

    Attributes:
        score: Continuous quality score in ``[0, 1]`` (validated; clamped upstream).
        rationale: Short natural-language justification from the judge.
        prompt: The EXACT prompt sent to the judge (recorded for auditability).
        rubric_version: Version of the rubric used (provenance).
        probe_id: The probe this verdict scores.
        model_id: The judge model id that produced the verdict (from config/backend).
        revision: The pinned judge model revision/commit.
        raw_output: The backend's raw text output (audit trail).
        prompt_tokens: Tokens in the prompt (judge cost — NOT system cost).
        output_tokens: Tokens generated by the judge (judge cost — NOT system cost).
    """

    score: float
    rationale: str
    prompt: str
    rubric_version: str
    probe_id: str
    model_id: str
    revision: str
    raw_output: str
    prompt_tokens: int
    output_tokens: int

    def __post_init__(self) -> None:
        if not 0.0 <= self.score <= 1.0:
            raise ValueError(f"JudgeScore.score must be in [0, 1], got {self.score}")
        if self.prompt_tokens < 0 or self.output_tokens < 0:
            raise ValueError("JudgeScore token counts must be non-negative")


@dataclass(frozen=True)
class JudgeRequest:
    """Everything a backend needs to produce a verdict for one probe."""

    prompt: str
    probe: Probe
    answer: str
    rubric: Rubric


@dataclass(frozen=True)
class JudgeRawOutput:
    """A backend's raw verdict, before clamping/packaging into a JudgeScore."""

    score: float
    rationale: str
    raw_text: str
    prompt_tokens: int
    output_tokens: int


@dataclass(frozen=True)
class JudgeUsage:
    """Token usage of the JUDGE — EXPLICITLY excluded from the system ``CostVector``.

    Judge tokens are an auditing/measurement cost, NOT a memory-system cost.  They
    are never summed into a ``CostVector`` and never enter the Memory ROI denominator
    (spec/02-metrics.md §1.3 exclusions).  This is a deliberately distinct type from
    ``CostVector`` so the two can never be confused or accidentally added together.
    """

    prompt_tokens: int = 0
    output_tokens: int = 0
    num_calls: int = 0

    def __add__(self, other: JudgeUsage) -> JudgeUsage:
        return JudgeUsage(
            prompt_tokens=self.prompt_tokens + other.prompt_tokens,
            output_tokens=self.output_tokens + other.output_tokens,
            num_calls=self.num_calls + other.num_calls,
        )


# --------------------------------------------------------------------------- #
# Backend protocol + helpers
# --------------------------------------------------------------------------- #
class JudgeBackend(Protocol):
    """A pluggable judge backend (stub for tests; live model in production)."""

    @property
    def model_id(self) -> str: ...

    @property
    def revision(self) -> str: ...

    def evaluate(self, request: JudgeRequest) -> JudgeRawOutput: ...


def _clamp01(value: float) -> float:
    return max(0.0, min(1.0, value))


def gold_to_str(gold: object) -> str:
    """Render a probe's gold reference as a stable string for prompts/scoring."""
    if isinstance(gold, str):
        return gold
    try:
        return json.dumps(gold, sort_keys=True, ensure_ascii=True)
    except (TypeError, ValueError):
        return repr(gold)


def build_prompt(probe: Probe, answer: str, rubric: Rubric) -> str:
    """Build the exact, deterministic judge prompt for one probe.

    The same (probe, answer, rubric) always yields byte-identical output, so the
    stored ``JudgeScore.prompt`` is a faithful, reproducible audit record.
    """
    gold_str = gold_to_str(probe.gold)
    return (
        "You are a strict evaluation judge. Score the AGENT ANSWER against the GOLD "
        "reference using the rubric below. Output ONLY a JSON object of the form "
        '{"score": <float 0..1>, "rationale": "<short text>"}.\n\n'
        f"## RUBRIC (version {rubric.version})\n{rubric.criteria}\n\n"
        f"## PROBE\nid: {probe.probe_id}\nkind: {probe.kind}\nquery: {probe.query}\n\n"
        f"## GOLD REFERENCE\n{gold_str}\n\n"
        f"## AGENT ANSWER\n{answer}\n\n"
        "## OUTPUT\nReturn ONLY the JSON object."
    )


def parse_judge_output(text: str) -> tuple[float, str]:
    """Parse a judge model's text output into ``(score, rationale)``.

    Expects a ``{"score": float, "rationale": str}`` JSON object; falls back to a
    bare-float search and uses the raw text as rationale.  Score is clamped to [0, 1].
    """
    match = re.search(r"\{.*\}", text, re.DOTALL)
    if match is not None:
        try:
            obj: object = json.loads(match.group(0))
        except (TypeError, ValueError):
            obj = None
        if isinstance(obj, dict):
            raw_score = obj.get("score")
            score = float(raw_score) if isinstance(raw_score, int | float) else 0.0
            rationale_obj = obj.get("rationale", "")
            rationale = rationale_obj if isinstance(rationale_obj, str) else str(rationale_obj)
            return _clamp01(score), rationale
    fallback = re.search(r"[01](?:\.\d+)?", text)
    score = _clamp01(float(fallback.group(0))) if fallback is not None else 0.0
    return score, text.strip()


# --------------------------------------------------------------------------- #
# Deterministic stub backend (unit tests)
# --------------------------------------------------------------------------- #
def _jaccard_score(answer: str, gold: object) -> float:
    """Deterministic token-overlap score in [0, 1] (exact match -> 1.0)."""
    gold_str = gold_to_str(gold)
    normalized_answer = answer.strip().lower()
    normalized_gold = gold_str.strip().lower()
    if normalized_answer == normalized_gold:
        return 1.0
    answer_tokens = set(normalized_answer.split())
    gold_tokens = set(normalized_gold.split())
    union = answer_tokens | gold_tokens
    if not union:
        return 0.0
    intersection = answer_tokens & gold_tokens
    return round(len(intersection) / len(union), 4)


class StubJudge:
    """Deterministic judge backend for unit tests (no real model required).

    Scores by token-level Jaccard overlap between the agent answer and the gold
    reference, anchored so an exact match scores 1.0 and a fully disjoint answer
    scores 0.0.  Fully deterministic: identical inputs always yield identical scores.
    Its identity is intentionally NOT that of the real configured judge.
    """

    def __init__(
        self,
        *,
        model_id: str = "stub-judge/deterministic",
        revision: str = "stub-v1",
    ) -> None:
        self._model_id = model_id
        self._revision = revision

    @property
    def model_id(self) -> str:
        return self._model_id

    @property
    def revision(self) -> str:
        return self._revision

    def evaluate(self, request: JudgeRequest) -> JudgeRawOutput:
        score = _jaccard_score(request.answer, request.probe.gold)
        rationale = f"stub deterministic judge: token-overlap score {score:.4f} vs gold reference"
        raw_text = json.dumps({"score": score, "rationale": rationale}, sort_keys=True)
        return JudgeRawOutput(
            score=score,
            rationale=rationale,
            raw_text=raw_text,
            prompt_tokens=len(request.prompt.split()),
            output_tokens=len(rationale.split()),
        )


# --------------------------------------------------------------------------- #
# Live (real-model) backend — gated behind LHMSB_LIVE_JUDGE=1
# --------------------------------------------------------------------------- #
class LiveJudge:
    """Real judge backend driven by a config-pinned text-generation callable.

    The model id and revision come from :class:`JudgeConfig` (config-driven; never
    hard-coded).  Construct via :func:`load_live_judge`, which enforces the env gate
    and lazily builds the generation callable so heavy ML deps stay optional.
    """

    def __init__(self, config: JudgeConfig, generate: Callable[[str], str]) -> None:
        self._config = config
        self._generate = generate

    @property
    def model_id(self) -> str:
        return self._config.model_id

    @property
    def revision(self) -> str:
        return self._config.revision

    def evaluate(self, request: JudgeRequest) -> JudgeRawOutput:
        raw_text = self._generate(request.prompt)
        score, rationale = parse_judge_output(raw_text)
        return JudgeRawOutput(
            score=score,
            rationale=rationale,
            raw_text=raw_text,
            prompt_tokens=len(request.prompt.split()),
            output_tokens=len(raw_text.split()),
        )


def _extract_generated_text(outputs: object) -> str:  # pragma: no cover - live only
    """Best-effort extraction of generated text from a transformers pipeline result."""
    if isinstance(outputs, list) and outputs:
        first = outputs[0]
        if isinstance(first, dict):
            value = first.get("generated_text", "")
            if isinstance(value, str):
                return value
        if isinstance(first, str):
            return first
    return str(outputs)


def _build_live_generate(config: JudgeConfig) -> Callable[[str], str]:  # pragma: no cover - live
    """Lazily build a text-generation callable pinned to ``config.model_id@revision``.

    Uses ``importlib`` so the missing optional dependency is a clean runtime error
    rather than an import-time/type-check failure.
    """
    try:
        transformers = importlib.import_module("transformers")
    except ImportError as exc:
        raise JudgeUnavailableError(
            "the live judge requires 'transformers'; install the live extras to enable it"
        ) from exc

    pipe = transformers.pipeline(
        "text-generation",
        model=config.model_id,
        revision=config.revision,
    )

    def _generate(prompt: str) -> str:
        outputs = pipe(prompt, max_new_tokens=256, do_sample=False)
        return _extract_generated_text(outputs)

    return _generate


def load_live_judge(config: JudgeConfig) -> JudgeBackend:
    """Load the real, config-pinned judge model.  Gated behind ``LHMSB_LIVE_JUDGE=1``.

    Args:
        config: The pinned judge configuration (model id + revision come from here).

    Returns:
        A :class:`JudgeBackend` driving the real model.

    Raises:
        JudgeUnavailableError: if the env gate is not set, or the model deps/weights
            cannot be loaded.
    """
    if os.environ.get(LIVE_JUDGE_ENV_FLAG) != "1":
        raise JudgeUnavailableError(
            f"live judge is disabled; set {LIVE_JUDGE_ENV_FLAG}=1 to load "
            f"{config.model_id!r} pinned at revision {config.revision!r}"
        )
    generate = _build_live_generate(config)
    return LiveJudge(config, generate)


# --------------------------------------------------------------------------- #
# Judge facade
# --------------------------------------------------------------------------- #
class Judge:
    """Sparse, boundary-only LLM judge over a pluggable backend.

    Use only for non-programmatically-decidable probes (open-ended synthesis,
    rationale checks) and only at episode boundaries.  Every verdict is packaged as
    a :class:`JudgeScore` and optionally appended to an audit :class:`JudgeTraceLog`.
    Judge token usage accumulates in :attr:`usage` (a :class:`JudgeUsage`, which is
    NOT a system ``CostVector``).
    """

    def __init__(self, backend: JudgeBackend, trace_log: JudgeTraceLog | None = None) -> None:
        self._backend = backend
        self._trace_log = trace_log
        self._usage = JudgeUsage()

    @property
    def usage(self) -> JudgeUsage:
        """Cumulative JUDGE token usage (excluded from system cost)."""
        return self._usage

    @property
    def model_id(self) -> str:
        return self._backend.model_id

    @property
    def revision(self) -> str:
        return self._backend.revision

    def score(
        self,
        probe: Probe,
        answer: str,
        rubric: Rubric,
        *,
        at_boundary: bool = True,
    ) -> JudgeScore:
        """Score one open-ended probe answer against the rubric.

        Args:
            probe: The probe being judged (open-ended / non-programmatic).
            answer: The agent's free-text answer.
            rubric: The fixed, versioned rubric.
            at_boundary: Must be True.  The judge is sparse and boundary-only; calling
                it per step or inside the agent loop raises :class:`JudgeUsageError`.

        Returns:
            A frozen :class:`JudgeScore` (score in [0, 1] + rationale + exact prompt).
        """
        if not at_boundary:
            raise JudgeUsageError(
                "the judge is sparse and boundary-only: it must not be called per step "
                "or inside the agent loop (only at episode boundaries)"
            )
        prompt = build_prompt(probe, answer, rubric)
        request = JudgeRequest(prompt=prompt, probe=probe, answer=answer, rubric=rubric)
        raw = self._backend.evaluate(request)
        score = _clamp01(raw.score)
        result = JudgeScore(
            score=score,
            rationale=raw.rationale,
            prompt=prompt,
            rubric_version=rubric.version,
            probe_id=probe.probe_id,
            model_id=self._backend.model_id,
            revision=self._backend.revision,
            raw_output=raw.raw_text,
            prompt_tokens=raw.prompt_tokens,
            output_tokens=raw.output_tokens,
        )
        self._usage = self._usage + JudgeUsage(
            prompt_tokens=raw.prompt_tokens,
            output_tokens=raw.output_tokens,
            num_calls=1,
        )
        if self._trace_log is not None:
            self._trace_log.append(
                JudgeTraceRecord(
                    probe_id=probe.probe_id,
                    model_id=self._backend.model_id,
                    revision=self._backend.revision,
                    rubric_version=rubric.version,
                    prompt=prompt,
                    answer=answer,
                    gold=gold_to_str(probe.gold),
                    score=score,
                    rationale=raw.rationale,
                    raw_output=raw.raw_text,
                    prompt_tokens=raw.prompt_tokens,
                    output_tokens=raw.output_tokens,
                )
            )
        return result
